done!
urfu-2017/markup-task-5 pull request #39
Opened 2017-11-07 18:42 UTC by Admirallll

2017-11-07 18:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-15 10:21 UTC, savichev-igor requested changes
Всё-таки я бы добавлял свойство CSS `cursor: pointer` на элементы, которые предполагают интерактивность (крестик, стрелочки, картинки, и т.д.)

Также разместил бы поровнее переключатели, а то уж как-то далеко они уезжают

![image](https://user-images.githubusercontent.com/7279995/32830938-986a156c-ca18-11e7-9d48-85bf3c494dc6.png)

🍅

2017-11-15 10:21 UTC, Savichev-Igor commented on index.html
> +                <div class="description">
`<p>`?

2017-11-15 10:21 UTC, Savichev-Igor commented on index.html
> +                    <img alt="огурец"  class="vegetable-photo" src="./images/cabbage.jpg">
Пробел лишний

2017-11-16 12:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-18 19:26 UTC, savichev-igor approved these changes

2017-11-18 19:27 UTC, Savichev-Igor commented
⭐️

2017-11-18 19:27 UTC, closed without merging