Лучше пока не смотреть
urfu-2017/markup-task-5 pull request #53
Opened 2017-11-08 10:57 UTC by Rolyx2

не дописал описания, лучше пока не проверять

2017-11-08 10:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-09 11:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-10 09:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-10 11:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-10 12:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-10 12:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-13 08:50 UTC, Mokoshka requested changes
- Будет круто, если крестик будет один на всю верстку
- А еще будет выглядеть аккуратнее, если изображения будут одного размера. Но не меняя исходные картинки

2017-11-13 08:50 UTC, Mokoshka commented on index.css
> +    height: 100%;
Здесь height: 100% никак не влияет на верстку

2017-11-13 08:50 UTC, Mokoshka commented on index.css
> +    display: none;
Почему бы не сделать сразу display: none у всех line, а потом отображать только конкретные для нужной радиокнопки

2017-11-13 08:50 UTC, Mokoshka commented on index.css
> +article:target ~ .modal-block
Не вижу класса modal-block в html

2017-11-13 08:50 UTC, Mokoshka commented on index.css
> +    padding: 0 50px 0 0;
padding-right?

2017-11-13 08:50 UTC, Mokoshka commented on index.css
> +[id='button3']:checked ~ .main .therd-line,
![image](https://user-images.githubusercontent.com/14892550/32716006-2887f33e-c876-11e7-8ac4-f63037efd39e.png)

2017-11-13 08:50 UTC, Mokoshka commented on index.css
> +.modal
Этот класс тоже не нашла

2017-11-13 08:50 UTC, Mokoshka commented on index.html
> +                    <p lang="ru">
Зачем здесь lang?

2017-11-13 08:50 UTC, Mokoshka commented on index.html
> +                <div class="photo-description">
Конструкция очень похожа на figure и figcaption, блок с подписью

2017-11-13 16:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-14 06:15 UTC, Mokoshka requested changes
- Куда-то овощи поехали 
![image](https://user-images.githubusercontent.com/14892550/32765608-14dc8f90-c92d-11e7-856d-7f235b5d4e33.png)
- А давай теперь сделаем так чтобы овощи были одного размера и по высоте и по ширине. Поможет свойство object-fit
- lang="ru" все еще у описания стоит, хотя у html указан язык уже

2017-11-14 06:15 UTC, Mokoshka commented on index.html
> +        <div>
Слишком много дивов, один точно лишний

2017-11-14 10:26 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-14 10:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-14 12:38 UTC, Mokoshka approved these changes

2017-11-14 12:38 UTC, closed without merging