done
urfu-2017/markup-task-5 pull request #57
Opened 2017-11-08 12:57 UTC by RomanDengin

2017-11-08 12:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-08 12:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-08 13:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-08 13:10 UTC, RomanDengin commented
ссылка "Посмотреть задание" почему-то не туда ведёт...
Я немного перепутал ссылки for, в результате чего по нажатию стрелочки открывался перец. Я поправил, чтобы открывалась вторая страница, но по "Посмотреть задание"  всё равно идёт переход на старую версию

2017-11-15 13:25 UTC, savichev-igor requested changes
В принципе решение рабочее, но местами выглядит не очень красиво

На большом мониторе выглядит вот так

![image](https://user-images.githubusercontent.com/7279995/32838466-d48ef5a2-ca32-11e7-8e55-55397482ae82.png)

Также из-за эффекта `hover` как-то всё не очень хорошо скачет

![image](https://user-images.githubusercontent.com/7279995/32838427-b0c886d8-ca32-11e7-8264-419b40c2f4ca.png)

Давай отцентруем галерею по вертикали и горизонтали?

:tomato:

2017-11-15 13:25 UTC, Savichev-Igor commented on index.css
> +    /*position: relative;*/
?

2017-11-15 13:25 UTC, Savichev-Igor commented on index.html
> +
А зачем эти пустые строки?

2017-11-15 13:25 UTC, Savichev-Igor commented on index.html
> +                    <img alt="" src="images/potato.jpg">
Пустой `alit` :<

2017-11-15 13:25 UTC, Savichev-Igor commented on index.html
> +
?

2017-11-15 13:25 UTC, Savichev-Igor commented on index.html
> +
?

2017-11-15 13:25 UTC, Savichev-Igor commented on index.html
> +        <form>
Ну здесь тэг `form` совершенно ведь ни к чему?

2017-11-15 13:25 UTC, Savichev-Igor commented on index.css
> +    vertical-align: middle;
Ты уверен, что это свойство необходимо?

2017-11-15 13:25 UTC, Savichev-Igor commented on index.css
> +    top: 0;
Ну а то что осталось темболее, ибо ты закомментировал `relative`

2017-11-15 13:25 UTC, Savichev-Igor commented on index.css
> +    align-content: center;
Кажется, что тут это свойство совершенно ни к чему, оно работает только при `display: flex;`

2017-11-15 13:25 UTC, Savichev-Igor commented on index.css
> +    align-content: center;
Лишнее..

2017-11-15 13:25 UTC, Savichev-Igor commented on index.css
> +    transform: translate(-50%, -50%);
Интересно)

2017-11-15 13:25 UTC, Savichev-Igor commented on index.css
> +    vertical-align: middle;
Кажется, что оно ничего не меняет :<

2017-11-15 13:25 UTC, Savichev-Igor commented on index.html
> +            <label for="cross">
Крестик вообще не видно, если честно

Добавь отступов и увеличь его

2017-11-15 13:25 UTC, Savichev-Igor commented on index.html
> +    </form>
А как же вложенность тэгов красивая?

2017-12-10 21:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-11 17:43 UTC, Savichev-Igor commented
Из-за эффекта `hover` до сих пор всё некрасиво скачет, когда перелистываем на вторую страницу, то появляется стрелка и все картинки смещаются вправо резко, что тоже не очень хорошо

`cursor: pointer` нету на интерактивных элементах

В общем жаль

2017-12-11 17:43 UTC, closed without merging

2017-12-11 17:44 UTC, savichev-igor reviewed
Из-за эффекта `hover` до сих пор всё некрасиво скачет, когда перелистываем на вторую страницу, то появляется стрелка и все картинки смещаются вправо резко, что тоже не очень хорошо

`cursor: pointer` нету на интерактивных элементах

В общем жаль :<

⭐️

2017-12-11 17:44 UTC, Savichev-Igor commented on index.css
> +    /*position: relative;*/
Почему не удалил?

2017-12-11 17:44 UTC, Savichev-Igor commented on index.css
> +html
Вынес бы наверх такие корневые стили