Мелкозёров  Леонид
urfu-2017/markup-task-5 pull request #6
Opened 2017-11-05 09:41 UTC by danmerus

2017-11-05 09:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 09:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 09:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 09:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 09:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 09:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 10:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 10:06 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 10:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 10:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 10:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 10:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-05 10:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-10 13:31 UTC, Dotokoto commented
1) Почему чекбоксы уползают наверх, когда в них тыкаешь? D: Очень неудобно
![2017-11-10 18-25-03](https://user-images.githubusercontent.com/8973726/32660406-8960428a-c644-11e7-9b78-5d4f3a6488a6.png)
2) Карточки яростно скачут при наведении. Надо чтобы не скакали, а только открывалось описание
3) в последних двух галереях нет картинок ( Давай больше овощей
4) будет прикольно, если сделаешь выравнивание открытой большой картинки по центру экрана
5) Странные черточки под картинками, которые еще и налезают на текст при его появлении
![2017-11-10 18-31-11](https://user-images.githubusercontent.com/8973726/32660608-63eb7992-c645-11e7-8070-c071ee9568df.png)

2017-11-10 13:34 UTC, Dotokoto commented
6) Переключатели не должны съезжать при открытии карточки
![2017-11-10 18-33-23](https://user-images.githubusercontent.com/8973726/32660712-b3fc92f4-c645-11e7-935a-0d61b51344bc.png)

2017-11-10 13:34 UTC, Dotokoto commented
:tomato:

2017-11-12 08:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-12 08:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-12 08:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-12 08:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-12 08:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-12 08:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-13 06:25 UTC, dotokoto requested changes
Уже лучше! Но еще есть, что поправить

2017-11-13 06:25 UTC, Dotokoto commented on index.html
> +    <div class="block1">
не хватает семантики, можно оформить это в `section`

2017-11-13 06:25 UTC, Dotokoto commented on index.html
> +            <div class="text">Наиболее распространенное холодостойкое влаголюбивое растение семейства
А тут можно оформить в `article`

2017-11-13 06:25 UTC, Dotokoto commented on index.html
> +<div class="spoiler">
больше семантики! Тут можно `main` вместо `div`

2017-11-13 06:25 UTC, Dotokoto commented on index.css
> +.pic3
Нужны более семантичные названия классов. Сейчас непонятно, чем они все отличаются и какую роль играют.
И почему их 4? Не хватит двух - для маленьких картинок и для больших на весь экран?

2017-11-13 06:26 UTC, Dotokoto commented
Картинка не влезает в высоту экрана. Надо сделать так, чтобы все картинки влезали независимо от их изначального размера
![2017-11-13 11-02-07](https://user-images.githubusercontent.com/8973726/32712246-60e0dedc-c865-11e7-8d20-15d6b21209cb.png)

2017-11-13 16:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-13 16:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-13 16:09 UTC, danmerus commented on index.css
> +.pic3
почему то разные блоки картинок уезжают по-разному, из-за этого костыли

2017-11-13 16:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-16 10:19 UTC, closed without merging